import type { ContextTag, Finding, Severity } from "@verglos/shared";

/**
 * Post-detection context-tag pass.
 *
 * Detectors emit findings based on syntactic patterns (a secret regex
 * hit, a template-literal SQL call, a Math.random() near "otp"). The
 * pattern is right, but the *context* determines whether it's a real
 * threat. A `Private Key PEM` in `docs/setup.md` is an example. A
 * `Bearer <token>` in `openapi.yml` is a spec sample. A `DATABASE_URL`
 * in `.github/workflows/ci.yml` is a service-container cred.
 *
 * This module walks findings and — where a file path matches a
 * well-known non-production shape — downgrades severity to `info` and
 * stamps `contextTag` + `originalSeverity` so the report can show
 * *why* the downgrade happened.
 *
 * Tag order matters: earlier tags win. The most specific patterns
 * (vendored-bundle, generated) come before broader ones (docs,
 * dev-fixture) so a `.min.js` under `docs/` still tags as
 * vendored-bundle.
 */

interface TagRule {
  tag: ContextTag;
  matches(finding: Finding): boolean;
}

/**
 * Vendored / minified / bundled third-party code. Not the app's own
 * source. A separate OSV-cross-reference pass (follow-up) can promote
 * these back to critical when the filename encodes a name@version
 * with a known CVE.
 */
function isVendoredBundle(file: string): boolean {
  return (
    /(^|\/)public\/(libraries|vendor|libs|lib|js\/vendor)\//i.test(file) ||
    /(^|\/)vendor\//i.test(file) ||
    /(^|\/)third[_-]?party\//i.test(file) ||
    /\.yarn\/(releases|plugins|sdks)\//.test(file) ||
    /(^|\/)node_modules\//.test(file) ||
    /\.min\.(js|css)$/i.test(file) ||
    /\.bundle\.(js|css)$/i.test(file) ||
    /(^|\/)\.pnp\.[a-z]+$/.test(file) ||
    // Framework-bundled assets under public/. Almost every Laravel /
    // Filament / Django / Rails project ships JS bundles here — these
    // are webpack / vite / esbuild output, not app code the maintainer
    // wrote line-by-line. Concrete ICP-300 false positives this catches:
    //   public/js/vendor.js         Bottelet DaybydayCRM (bundled jQuery)
    //   public/js/app.js            Ctrlpanel (webpack app bundle)
    //   public/js/filament/**       Paymenter (Filament admin JS)
    //   public/plugins/jquery/*     Ctrlpanel (Laravel jQuery vendor)
    /(^|\/)public\/(js|css|assets|dist|build|plugins|themes)\//i.test(file) ||
    // Distribution binaries dropped into `binaries/` or `bin/` inside a
    // package. Yarn Berry ships as a single yarn-<ver>.cjs blob that
    // trips the secrets and misconfig detectors on eval / long entropy
    // strings — the .yarn/releases/ rule catches it when it lives under
    // .yarn/, but repos that vendor a copy inside `packages/*/binaries/`
    // (webiny) or `bin/` need the same treatment.
    //
    // Concrete ICP-300 false positive fixed by this:
    //   webiny-webiny-js:
    //     packages/create-webiny-project/src/services/SetupYarn/binaries/yarn-4.17.1.cjs
    //     — 6 D4-001 / D5-003 crits + highs on a vendored yarn CLI.
    /(^|\/)(?:binaries|bin)\/[^/]+\.(?:cjs|mjs|js)$/i.test(file) ||
    // Versioned distribution filenames anywhere in the tree —
    // `something-1.2.3.js` / `something@1.2.3.min.js`. If the filename
    // encodes a name@version, it's a vendored copy of a library. The
    // vendored-cves detector (D6-002) already parses this shape to
    // cross-reference OSV; mirroring that here means the file's other
    // detectors get the same context treatment.
    /(?:^|\/)[a-z0-9][a-z0-9._-]*[-@]\d+(?:\.\d+){1,3}(?:[-.][a-z0-9]+)*(?:\.min|\.bundle)?\.(?:c?js|mjs)$/i.test(file)
  );
}

/**
 * Generated code. Big autogenerated .d.ts blobs sometimes carry
 * example strings in JSDoc that look like secrets.
 */
function isGenerated(file: string): boolean {
  return (
    /(^|\/)generated\//i.test(file) ||
    /\.generated\.[jt]sx?$/i.test(file) ||
    /(^|\/)__generated__\//.test(file) ||
    /(^|\/)_generated\//.test(file) ||
    /internal\/types\/generated\//i.test(file)
  );
}

/**
 * Developer fixture files: local docker compose, .env samples, dev
 * container configs. The values are meant to be seen by developers
 * running locally — they are not production creds.
 */
function isDevFixture(file: string): boolean {
  return (
    /(^|\/)\.env(\.|$)/.test(file) ||
    /\.env\.example$/i.test(file) ||
    /\.env\.local$/i.test(file) ||
    /\.env\.dev(elopment)?$/i.test(file) ||
    /\.env\.test$/i.test(file) ||
    /docker-compose.*\.ya?ml$/i.test(file) ||
    /(^|\/)docker\//i.test(file) ||
    // docker-compose/ as a directory (files inside it, not just the
    // yml at root). lobe-chat has `docker-compose/production/grafana/
    // init_data.json` — same dev-only stack, different filename.
    /(^|\/)docker-compose\//i.test(file) ||
    /(^|\/)\.devcontainer\//i.test(file) ||
    /(^|\/)Dockerfile(\.[^/]+)?$/.test(file) ||
    // Deployment templates. Helm values.yaml and Kubernetes/OpenShift
    // manifests carry placeholder secrets that the operator fills in
    // per environment. The template file itself is documentation.
    /(^|\/)deploy(ment)?s?\//i.test(file) ||
    /(^|\/)helm\//i.test(file) ||
    /(^|\/)charts?\//i.test(file) ||
    /(^|\/)k8s\//i.test(file) ||
    /(^|\/)kubernetes\//i.test(file) ||
    /(^|\/)manifests?\//i.test(file) ||
    /values(?:\.[a-z-]+)?\.ya?ml$/i.test(file) ||
    /(^|\/)terraform\//i.test(file) ||
    /(^|\/)ansible\//i.test(file)
  );
}

/**
 * CI workflow files. Service-container credentials for Postgres /
 * Redis / MinIO / whatever the pipeline spins up. Well-known values
 * used only in ephemeral CI runners.
 *
 * Includes hosted-CI providers beyond the obvious GitHub Actions:
 * .depot/ (Depot.dev), .buildkite/, .circleci/, .woodpecker/,
 * .drone.yml, gitlab, azure-pipelines.
 */
function isCiWorkflow(file: string): boolean {
  return (
    /\.github\/workflows\//.test(file) ||
    /\.gitlab-ci\.ya?ml$/.test(file) ||
    /(^|\/)\.circleci\//.test(file) ||
    /(^|\/)\.travis\.ya?ml$/.test(file) ||
    /(^|\/)\.buildkite\//.test(file) ||
    /(^|\/)\.woodpecker\//.test(file) ||
    /(^|\/)\.depot\/workflows\//.test(file) ||
    /(^|\/)\.drone\.ya?ml$/.test(file) ||
    /(^|\/)azure-pipelines/.test(file)
  );
}

/**
 * Build tool configs. Wildcard CORS in webpack-dev-server / rspack /
 * vite dev configs is by design — the whole point is a permissive
 * local dev environment. Never ships to production.
 */
function isBuildConfig(file: string): boolean {
  return (
    /webpack(DevServer)?\.config\.[jt]s$/i.test(file) ||
    /webpack\.[^/]*\.(m|c)?[jt]sx?$/i.test(file) ||
    /rspack\.config\.(m|c)?[jt]sx?$/i.test(file) ||
    /vite\.config\.(m|c)?[jt]sx?$/i.test(file) ||
    /rollup\.config\.(m|c)?[jt]sx?$/i.test(file) ||
    /esbuild\.config\.(m|c)?[jt]sx?$/i.test(file) ||
    /(^|\/)build\/config\//i.test(file) ||
    /(^|\/)config\/webpack/i.test(file)
  );
}

/**
 * Docs. Findings in markdown / restructuredtext / adoc files are
 * almost never real credentials — they're example creds embedded in
 * setup guides ("your DATABASE_URL should look like postgres://...").
 */
function isDocs(file: string): boolean {
  return (
    /\.(md|mdx|rst|adoc)$/i.test(file) ||
    /(^|\/)docs?\//i.test(file) ||
    /(^|\/)CONTRIBUTING(\.[^/]+)?$/i.test(file) ||
    /(^|\/)README(\.[^/]+)?$/i.test(file) ||
    /(^|\/)CHANGELOG(\.[^/]+)?$/i.test(file)
  );
}

/**
 * OpenAPI / Swagger specs. The `example` field of a request body is
 * the whole point of the spec — flagging it as a leaked secret is
 * absurd.
 */
function isApiSpecExample(file: string): boolean {
  return (
    /openapi.*\.ya?ml$/i.test(file) ||
    /swagger.*\.ya?ml$/i.test(file) ||
    /\.openapi\.[a-z]+$/i.test(file) ||
    /api\/v\d+\/.*\.(ya?ml|json)$/i.test(file) ||
    /(^|\/)apidocs?\//i.test(file)
  );
}

/**
 * Test files. The scanner already has a coarse `context: "test"` flag
 * on some detectors — this tag catches the rest, and stamps the tag
 * name so reports render "why was this info instead of critical."
 */
function isTestFixture(file: string): boolean {
  return (
    /(^|\/)test(s)?\//i.test(file) ||
    /(^|\/)__tests__\//.test(file) ||
    /(^|\/)spec\//.test(file) ||
    /(^|\/)cypress\//.test(file) ||
    /(^|\/)playwright\//.test(file) ||
    /(^|\/)e2e[_-]tests?\//.test(file) ||
    /\.(test|spec)\.[jt]sx?$/.test(file) ||
    // Compound-suffix test files: e2e-spec.ts, integration.test.ts,
    // unit.test.ts, controller.e2e-spec.ts, foo.it.ts. Cal.com uses
    // `.e2e-spec.ts`; nest projects commonly use `.integration.ts`.
    /[.-](?:e2e[.-]?(?:test|spec)|integration[.-](?:test|spec)|unit[.-](?:test|spec)|it)\.[jt]sx?$/.test(file) ||
    /\.e2e[.-]spec\.[jt]sx?$/.test(file) ||
    /(^|\/)testUtils?(\.|\/)/i.test(file) ||
    /(^|\/)__mocks__\//.test(file) ||
    /(^|\/)fixtures?\//i.test(file) ||
    // Mock data — hasura frontend/.../mock/index.ts, n8n
    // benchmark/scripts/mock-api/mappings/mockApiData.json, etc.
    // Any mock/ segment plus common mock-flavoured names.
    /(^|\/)mocks?\//i.test(file) ||
    /(^|\/)mock[_-](?:api|server|data)\//i.test(file) ||
    /(^|\/)mockData\//i.test(file) ||
    /(^|\/)__fixtures__\//i.test(file) ||
    // Benchmark scripts — same shape as tests, throwaway data.
    /(^|\/)benchmarks?\//i.test(file) ||
    // Sample/example directories.
    /(^|\/)examples?\//i.test(file) ||
    /(^|\/)samples?\//i.test(file) ||
    // Tutorial / book / lesson content — same shape as examples,
    // full chapter-numbered directories of demo code. Concrete
    // ICP-300 false positives fixed by this:
    //   async-labs-saas: book/10-begin/api/server/api/index.ts
    //   book/{4,5,6,7,8,9,10}-{begin,end,end-functional}/**  (~15 dup FPs)
    /(^|\/)book\//i.test(file) ||
    /(^|\/)tutorials?\//i.test(file) ||
    /(^|\/)chapters?\//i.test(file) ||
    /(^|\/)lessons?\//i.test(file) ||
    /(^|\/)walkthroughs?\//i.test(file) ||
    /(^|\/)workshops?\//i.test(file)
  );
}

/**
 * Big data / content JSON blobs. Skills catalogs, i18n dictionaries,
 * pre-rendered content packs. Detectors that look for code-shape
 * patterns (Math.random, eval, console.log with sensitive terms, SQL
 * interpolation) fire on prose inside JSON string values — every
 * mention of "console.log('api key:', k)" inside a code-example
 * markdown-in-JSON blob becomes an emitted finding.
 *
 * Concrete ICP-300 false positives fixed by this:
 *   jeremylongshore/claude-code-plugins-plus-skills:
 *     marketplace/public/data/skills-catalog.json  →  1050 FPs
 *     marketplace/src/data/skills-catalog.json     →  1050 FPs
 *   (D8-001 medium: 1922, D4-001 info: 214 — the outlier repo of the
 *   300-repo campaign, ~4000 findings from one FP source.)
 *
 * Kept strict:
 *   1. Must live under a data-flavoured directory
 *      (public/data/, src/data/, content/data/, static/data/,
 *      assets/data/, or a bare data/ segment).
 *   2. Must be .json / .jsonl / .ndjson (not .env, not config files
 *      that happen to be JSON like tsconfig.json).
 * A real secret inside a small config .json is still caught.
 */
function isDataContent(file: string): boolean {
  if (!/\.(?:json|jsonl|ndjson)$/i.test(file)) return false;
  return (
    /(^|\/)(?:public|src|content|static|assets|marketplace)\/data\//i.test(file) ||
    /(^|\/)data\/(?:catalogs?|content|manifests?|generated|dumps?|exports?|snapshots?|packs?)\//i.test(file) ||
    /(?:^|\/)(?:content|catalog|manifest|dump|export|snapshot|pack)-catalog\.(?:json|jsonl|ndjson)$/i.test(file) ||
    /(?:^|\/)skills?[-_]catalog\.(?:json|jsonl|ndjson)$/i.test(file)
  );
}

/**
 * The tag rules, in application order. First match wins.
 * More-specific rules come first (vendored-bundle before docs) so
 * a minified library file that happens to live under `docs/` still
 * tags as vendored-bundle.
 */
const TAG_RULES: TagRule[] = [
  {
    tag: "vendored-bundle",
    matches: (f) => !!f.file && isVendoredBundle(f.file),
  },
  {
    // Data / content JSON blobs. Placed early so a skills-catalog.json
    // under public/data/ is tagged as data-content, not docs.
    tag: "data-content",
    matches: (f) => !!f.file && isDataContent(f.file),
  },
  { tag: "generated", matches: (f) => !!f.file && isGenerated(f.file) },
  { tag: "test-fixture", matches: (f) => !!f.file && isTestFixture(f.file) },
  { tag: "dev-fixture", matches: (f) => !!f.file && isDevFixture(f.file) },
  { tag: "ci-workflow", matches: (f) => !!f.file && isCiWorkflow(f.file) },
  { tag: "build-config", matches: (f) => !!f.file && isBuildConfig(f.file) },
  {
    tag: "api-spec-example",
    matches: (f) => !!f.file && isApiSpecExample(f.file),
  },
  { tag: "docs", matches: (f) => !!f.file && isDocs(f.file) },
];

const DOWNGRADED: Severity = "info";

/**
 * Detector rules that MUST NOT be downgraded by the context-tag
 * pass. These are already context-aware — the vendored-cves
 * detector (D6-002) specifically looks at files under
 * public/libraries/ / vendor/ and reports only when the vendored
 * name@version has a known CVE. Downgrading those to `info` because
 * the file lives in a vendored path would defeat the whole point.
 */
const CONTEXT_AWARE_RULES = new Set<string>([
  "D6-002", // vendored-cves — differentiator, already precision-tuned
]);

/**
 * Walks findings and tags each one where the file path matches a
 * non-production context. Tagged findings have their severity set
 * to `info` and preserve the raw severity on `originalSeverity`.
 *
 * Rules in CONTEXT_AWARE_RULES are exempt — their detectors already
 * run per-finding context checks and the coarse path heuristic here
 * would otherwise silence the differentiator.
 *
 * `strict` (v1.6): in --strict mode we still STAMP the contextTag
 * and originalSeverity so the reporter can explain the tag, but we
 * do NOT downgrade severity to info. Strict callers want every
 * finding counted at full severity, matching the strict behavior of
 * context.ts's classifyFindings for the `test` context. Before this,
 * strict + a test-fixture path resulted in severity=info anyway,
 * silently defeating --strict.
 *
 * Never mutates input; returns new finding objects.
 */
export function applyContextTags(
  findings: Finding[],
  strict = false,
): Finding[] {
  return findings.map((finding) => {
    if (finding.rule && CONTEXT_AWARE_RULES.has(finding.rule)) return finding;
    for (const rule of TAG_RULES) {
      if (!rule.matches(finding)) continue;
      return {
        ...finding,
        contextTag: rule.tag,
        originalSeverity: finding.severity,
        severity: strict ? finding.severity : DOWNGRADED,
      };
    }
    return finding;
  });
}
