import type { ContextTag, Finding, Severity } from "@verglos/shared";

/**
 * Post-detection context-tag pass.
 *
 * Detectors emit findings based on syntactic patterns (a secret regex
 * hit, a template-literal SQL call, a Math.random() near "otp"). The
 * pattern is right, but the *context* determines whether it's a real
 * threat. A `Private Key PEM` in `docs/setup.md` is an example. A
 * `Bearer <token>` in `openapi.yml` is a spec sample. A `DATABASE_URL`
 * in `.github/workflows/ci.yml` is a service-container cred.
 *
 * This module walks findings and — where a file path matches a
 * well-known non-production shape — downgrades severity to `info` and
 * stamps `contextTag` + `originalSeverity` so the report can show
 * *why* the downgrade happened.
 *
 * Tag order matters: earlier tags win. The most specific patterns
 * (vendored-bundle, generated) come before broader ones (docs,
 * dev-fixture) so a `.min.js` under `docs/` still tags as
 * vendored-bundle.
 */

interface TagRule {
  tag: ContextTag;
  matches(finding: Finding): boolean;
}

/**
 * Vendored / minified / bundled third-party code. Not the app's own
 * source. A separate OSV-cross-reference pass (follow-up) can promote
 * these back to critical when the filename encodes a name@version
 * with a known CVE.
 */
function isVendoredBundle(file: string): boolean {
  return (
    /(^|\/)public\/(libraries|vendor|libs|lib|js\/vendor)\//i.test(file) ||
    /(^|\/)vendor\//i.test(file) ||
    /(^|\/)third[_-]?party\//i.test(file) ||
    /\.yarn\/(releases|plugins|sdks)\//.test(file) ||
    /(^|\/)node_modules\//.test(file) ||
    /\.min\.(js|css)$/i.test(file) ||
    /\.bundle\.(js|css)$/i.test(file) ||
    /(^|\/)\.pnp\.[a-z]+$/.test(file)
  );
}

/**
 * Generated code. Big autogenerated .d.ts blobs sometimes carry
 * example strings in JSDoc that look like secrets.
 */
function isGenerated(file: string): boolean {
  return (
    /(^|\/)generated\//i.test(file) ||
    /\.generated\.[jt]sx?$/i.test(file) ||
    /(^|\/)__generated__\//.test(file) ||
    /(^|\/)_generated\//.test(file) ||
    /internal\/types\/generated\//i.test(file)
  );
}

/**
 * Developer fixture files: local docker compose, .env samples, dev
 * container configs. The values are meant to be seen by developers
 * running locally — they are not production creds.
 */
function isDevFixture(file: string): boolean {
  return (
    /(^|\/)\.env(\.|$)/.test(file) ||
    /\.env\.example$/i.test(file) ||
    /\.env\.local$/i.test(file) ||
    /\.env\.dev(elopment)?$/i.test(file) ||
    /\.env\.test$/i.test(file) ||
    /docker-compose.*\.ya?ml$/i.test(file) ||
    /(^|\/)docker\//i.test(file) ||
    /(^|\/)\.devcontainer\//i.test(file) ||
    /(^|\/)Dockerfile(\.[^/]+)?$/.test(file)
  );
}

/**
 * CI workflow files. Service-container credentials for Postgres /
 * Redis / MinIO / whatever the pipeline spins up. Well-known values
 * used only in ephemeral CI runners.
 *
 * Includes hosted-CI providers beyond the obvious GitHub Actions:
 * .depot/ (Depot.dev), .buildkite/, .circleci/, .woodpecker/,
 * .drone.yml, gitlab, azure-pipelines.
 */
function isCiWorkflow(file: string): boolean {
  return (
    /\.github\/workflows\//.test(file) ||
    /\.gitlab-ci\.ya?ml$/.test(file) ||
    /(^|\/)\.circleci\//.test(file) ||
    /(^|\/)\.travis\.ya?ml$/.test(file) ||
    /(^|\/)\.buildkite\//.test(file) ||
    /(^|\/)\.woodpecker\//.test(file) ||
    /(^|\/)\.depot\/workflows\//.test(file) ||
    /(^|\/)\.drone\.ya?ml$/.test(file) ||
    /(^|\/)azure-pipelines/.test(file)
  );
}

/**
 * Build tool configs. Wildcard CORS in webpack-dev-server / rspack /
 * vite dev configs is by design — the whole point is a permissive
 * local dev environment. Never ships to production.
 */
function isBuildConfig(file: string): boolean {
  return (
    /webpack(DevServer)?\.config\.[jt]s$/i.test(file) ||
    /webpack\.[^/]*\.(m|c)?[jt]sx?$/i.test(file) ||
    /rspack\.config\.(m|c)?[jt]sx?$/i.test(file) ||
    /vite\.config\.(m|c)?[jt]sx?$/i.test(file) ||
    /rollup\.config\.(m|c)?[jt]sx?$/i.test(file) ||
    /esbuild\.config\.(m|c)?[jt]sx?$/i.test(file) ||
    /(^|\/)build\/config\//i.test(file) ||
    /(^|\/)config\/webpack/i.test(file)
  );
}

/**
 * Docs. Findings in markdown / restructuredtext / adoc files are
 * almost never real credentials — they're example creds embedded in
 * setup guides ("your DATABASE_URL should look like postgres://...").
 */
function isDocs(file: string): boolean {
  return (
    /\.(md|mdx|rst|adoc)$/i.test(file) ||
    /(^|\/)docs?\//i.test(file) ||
    /(^|\/)CONTRIBUTING(\.[^/]+)?$/i.test(file) ||
    /(^|\/)README(\.[^/]+)?$/i.test(file) ||
    /(^|\/)CHANGELOG(\.[^/]+)?$/i.test(file)
  );
}

/**
 * OpenAPI / Swagger specs. The `example` field of a request body is
 * the whole point of the spec — flagging it as a leaked secret is
 * absurd.
 */
function isApiSpecExample(file: string): boolean {
  return (
    /openapi.*\.ya?ml$/i.test(file) ||
    /swagger.*\.ya?ml$/i.test(file) ||
    /\.openapi\.[a-z]+$/i.test(file) ||
    /api\/v\d+\/.*\.(ya?ml|json)$/i.test(file) ||
    /(^|\/)apidocs?\//i.test(file)
  );
}

/**
 * Test files. The scanner already has a coarse `context: "test"` flag
 * on some detectors — this tag catches the rest, and stamps the tag
 * name so reports render "why was this info instead of critical."
 */
function isTestFixture(file: string): boolean {
  return (
    /(^|\/)test(s)?\//i.test(file) ||
    /(^|\/)__tests__\//.test(file) ||
    /(^|\/)spec\//.test(file) ||
    /(^|\/)cypress\//.test(file) ||
    /(^|\/)playwright\//.test(file) ||
    /(^|\/)e2e[_-]tests?\//.test(file) ||
    /\.(test|spec)\.[jt]sx?$/.test(file) ||
    /(^|\/)testUtils?(\.|\/)/i.test(file) ||
    /(^|\/)__mocks__\//.test(file) ||
    /(^|\/)fixtures?\//i.test(file)
  );
}

/**
 * The tag rules, in application order. First match wins.
 * More-specific rules come first (vendored-bundle before docs) so
 * a minified library file that happens to live under `docs/` still
 * tags as vendored-bundle.
 */
const TAG_RULES: TagRule[] = [
  {
    tag: "vendored-bundle",
    matches: (f) => !!f.file && isVendoredBundle(f.file),
  },
  { tag: "generated", matches: (f) => !!f.file && isGenerated(f.file) },
  { tag: "test-fixture", matches: (f) => !!f.file && isTestFixture(f.file) },
  { tag: "dev-fixture", matches: (f) => !!f.file && isDevFixture(f.file) },
  { tag: "ci-workflow", matches: (f) => !!f.file && isCiWorkflow(f.file) },
  { tag: "build-config", matches: (f) => !!f.file && isBuildConfig(f.file) },
  {
    tag: "api-spec-example",
    matches: (f) => !!f.file && isApiSpecExample(f.file),
  },
  { tag: "docs", matches: (f) => !!f.file && isDocs(f.file) },
];

const DOWNGRADED: Severity = "info";

/**
 * Walks findings and tags each one where the file path matches a
 * non-production context. Tagged findings have their severity set
 * to `info` and preserve the raw severity on `originalSeverity`.
 *
 * Never mutates input; returns new finding objects.
 */
export function applyContextTags(findings: Finding[]): Finding[] {
  return findings.map((finding) => {
    for (const rule of TAG_RULES) {
      if (!rule.matches(finding)) continue;
      return {
        ...finding,
        contextTag: rule.tag,
        originalSeverity: finding.severity,
        severity: DOWNGRADED,
      };
    }
    return finding;
  });
}
