import { importBoundedJson, type ImportedDocument } from "./importer-registry.js";
export interface ImportedCycloneDx { readonly format: "cyclonedx"; readonly version: string; readonly serialNumber?: string; readonly sourceDigest: ImportedDocument["sourceDigest"]; readonly components: readonly Record<string, unknown>[]; readonly dependencies: readonly Record<string, unknown>[]; readonly document: Record<string, unknown>; }
export class CycloneDxImportError extends Error { override readonly name = "CycloneDxImportError"; constructor(readonly code: "MALFORMED_COMPONENT" | "UNSUPPORTED_VERSION", message: string) { super(message); } }
export function importCycloneDx(bytes: Uint8Array): ImportedCycloneDx {
  const imported = importBoundedJson(bytes); if (imported.format !== "cyclonedx") throw new CycloneDxImportError("MALFORMED_COMPONENT", "Document is not CycloneDX.");
  const version = imported.version; const document = imported.document as Record<string, unknown>; const components = document.components ?? []; const dependencies = document.dependencies ?? [];
  if (!Array.isArray(components) || components.some((entry) => typeof entry !== "object" || entry === null)) throw new CycloneDxImportError("MALFORMED_COMPONENT", "CycloneDX components must be objects.");
  for (const component of components as Record<string, unknown>[]) { if (typeof component.type !== "string" || (typeof component.name !== "string" && typeof component["bom-ref"] !== "string")) throw new CycloneDxImportError("MALFORMED_COMPONENT", "CycloneDX components require type and name or bom-ref."); if (component.hashes !== undefined && (!Array.isArray(component.hashes) || (component.hashes as unknown[]).some((hash) => typeof hash !== "object" || hash === null))) throw new CycloneDxImportError("MALFORMED_COMPONENT", "CycloneDX hashes must be objects."); }
  if (!Array.isArray(dependencies) || dependencies.some((entry) => typeof entry !== "object" || entry === null)) throw new CycloneDxImportError("MALFORMED_COMPONENT", "CycloneDX dependencies must be objects."); return { format: "cyclonedx", version, ...(typeof document.serialNumber === "string" ? { serialNumber: document.serialNumber } : {}), sourceDigest: imported.sourceDigest, components: components as Record<string, unknown>[], dependencies: dependencies as Record<string, unknown>[], document };
}
