import { createHash } from "node:crypto";
import { canonicalizeJson } from "./schema.js";
import { parseObservation, type ObservationDocument } from "./observation.js";
import type { NativeFindingProjection } from "./finding-adapter.js";

export function nativeFindingToObservation(input: { readonly finding: NativeFindingProjection; readonly subjectId: string; readonly producerId: string; readonly runId: `urn:uuid:${string}`; readonly rawEvidenceDigest?: `sha256:${string}` }): ObservationDocument {
  const finding = input.finding; const location = finding.file ? { kind: "source" as const, path: finding.file, startLine: finding.line ?? 1, ...(finding.column !== undefined ? { startColumn: finding.column } : {}), ...(finding.endLine !== undefined ? { endLine: finding.endLine } : {}) } : { kind: "artifact" as const, path: "finding.json" };
  const normalized = (["critical", "high", "medium", "low", "info"] as const).includes(finding.severity.toLowerCase() as never) ? finding.severity.toLowerCase() as ObservationDocument["severity"]["normalized"] : "unknown";
  const confidenceScore = typeof finding.confidence === "number" ? finding.confidence : undefined; const confidenceLevel = confidenceScore === undefined ? "unknown" : confidenceScore >= 0.9 ? "certain" : confidenceScore >= 0.7 ? "high" : confidenceScore >= 0.4 ? "medium" : confidenceScore > 0 ? "low" : "unknown";
  const base = { schemaId: "urn:verglos:schema:observation", schemaVersion: "1.0.0", observationId: "urn:uuid:00000000-0000-4000-8000-000000000000", subjectId: input.subjectId, origin: { kind: "native" as const, producerId: input.producerId, runId: input.runId, ruleId: finding.rule ?? finding.detector, ...(input.rawEvidenceDigest ? { rawEvidenceDigest: input.rawEvidenceDigest } : {}) }, coverageClass: "native" as const, category: finding.detector, title: finding.title, description: finding.description, locations: [location], severity: { original: { system: "verglos.legacy", value: finding.originalSeverity ?? finding.severity }, normalized, mapping: { id: "verglos.severity.v1", version: "1.0.0" } }, confidence: { ...(typeof finding.confidence === "number" ? { original: finding.confidence, ...(confidenceScore !== undefined ? { score: confidenceScore } : {}) } : { original: String(finding.confidence) }), level: confidenceLevel, method: "verglos.native-confidence", mappingVersion: "1.0.0" }, ...(finding.fix ? { remediation: { summary: finding.fix } } : {}), evidence: finding.snippet ? [{ kind: "excerpt" as const, classification: "non-sensitive" as const, handling: "included" as const, description: "legacy finding excerpt", content: finding.snippet.slice(0, 4096) }] : [], references: finding.refs.filter((url) => url.startsWith("https://")).map((url) => ({ url })), extensions: { "verglos.native-finding": { findingId: finding.findingId, detector: finding.detector, ...(finding.legacyVerified !== undefined ? { legacyVerified: finding.legacyVerified } : {}) } } };
  const { observationId: _placeholder, ...identity } = base; const digest = createHash("sha256").update(canonicalizeJson(identity)).digest("hex"); const observationId = `urn:uuid:${digest.slice(0, 8)}-${digest.slice(8, 12)}-4${digest.slice(13, 16)}-8${digest.slice(17, 20)}-${digest.slice(20, 32)}` as const;
  return parseObservation({ ...base, observationId });
}
